### ISSUE TITLE
[1.18.2] Invalid modId found

### ISSUE THREAD

**Issue by aking4125** [Trinsdar/NetherEndBiomeInjector#1]
Hello,

Upon adding this mod to be used with [Cinderscapes Reforged](https://www.curseforge.com/minecraft/mc-mods/cinderscapes-reforged). The client crashes with the following text upon load:

`[main/FATAL] [ne.mi.fm.lo.mo.ModInfo/]: Invalid modId found in file C:\MultiMC\instances\Epic Marvels 4 [1.18.1] [DEV]\.minecraft\mods\FabricBiomeApiReforged-2.0.jar - fabric-biome-api does not match the standard: ^[a-z][a-z0-9_]{1,63}$`

No crash report is created so uploading this: 
[debug.log](https://github.com/Reforged-Mods/FabricBiomeApiReforged/files/8839097/debug.log)

Any ideas? Removing this mod allows the pack to continue normally. 

Running Forge 40.1.31 - 1.18.2

**Comment by Jukabofy** [comment]
I can confirm this issue, the game crash at the start and it shows me the same error

**Comment by Trinsdar** [comment]
Seems for some reason forge doesn't allow hyphens in the modid now? Wtf

**Comment by WarlordWossman** [comment]
now getting this with the new versions: https://www.toptal.com/developers/hastebin/iheyiniwum.sql

**Comment by Trinsdar** [comment]
Oh oops, i knew what I did, as a metter of fact this you don't even have to wait for a new version, you can just open the jar in some archive manager, navigate to cinderscapes.mixin.json, and remove SoundEventAccessir from the list in the json

**Comment by WarlordWossman** [comment]
did that, now the crash looks like this: https://www.toptal.com/developers/hastebin/owisaxuheq.sql

seems to be the same as #2
