### ISSUE TITLE
2.0.2 crash

### ISSUE THREAD

**Issue by WarlordWossman** [Trinsdar/NetherEndBiomeInjector#4]
Looks like something is still going wrong with 2.0.2 version of fabricbiomeAPI and cinderscapes:
https://www.toptal.com/developers/hastebin/wamikikebo.properties

**Comment by Trinsdar** [comment]
Oh ffs, though this is what I get for not loading a world first to make sure it didn't crash

**Comment by Trinsdar** [comment]
uhh currently having difficulties fixing this, seems on forge lambda injects don't work?
